version: "2.4"
services:
  mysql:
    image: mysql:8.0
    container_name: mysqldb
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.2
    ports:
      - 8181:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    container_name: mongodb
